[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_helpers_meena"
version = "0.0.1"
description = "AI helpers package"
authors = [{name="Meena"}]
readme = "README.md"
license = {text="MIT"}

[tool.setuptools]
packages = ["ai_helpers_meena"]
